const translations = {
    tr: {
        about: "Hakkımızda",
        features: "Özellikler",
        contact: "İletişim",
        login: "Giriş Yap",
        loginTitle: "LUMINEX - Giriş Yap",
        heroTitle: "Sağlıkta Dijital Dönüşüm",
        heroSubtitle: "LUMINEX ile sağlık hizmetlerine tek tıkla ulaşın. Randevularınızı planlayın, sonuçlarınızı görün.",
        cardAppointmentTitle: "Randevu Al",
        cardAppointmentDesc: "Hastane ve hekim seçerek kolayca randevu oluşturun.",
        cardResultsTitle: "Tahlil Sonuçları",
        cardResultsDesc: "Laboratuvar ve görüntüleme sonuçlarınıza anında erişin.",
        cardDoctorsTitle: "Doktor Bul",
        cardDoctorsDesc: "Uzman hekim kadromuzu inceleyin ve bilgi alın.",
        cardSymptomTitle: "Neyim Var?",
        cardSymptomDesc: "Şikayetlerinize göre yapay zeka destekli ön teşhis.",
        servicesTitle: "Online İşlemler",
        servicePrescriptions: "E-Reçetelerim",
        serviceRadiology: "Radyoloji Görüntüleri",
        serviceReports: "Raporlarım",
        serviceVisits: "Ziyaretlerim",
        serviceEmergency: "Acil Durum",
        serviceSupport: "Canlı Destek",
        featuredDoctorsTitle: "Öne Çıkan Doktorlarımız",
        featuredDoctorsSubtitle: "Alanında uzman kadromuzla yanınızdayız.",
        register: "Ücretsiz Kayıt Ol",
        aboutTitle: "Modern Sağlık Deneyimi",
        aboutText: "Luminex, geleneksel sağlık hizmetlerini dijital dünyanın hızı ve kolaylığıyla birleştirir. Size zaman kazandıran, stresi azaltan ve sağlık yönetiminizi kolaylaştıran bir platform sunuyoruz.",
        missionTitle: "Misyonumuz",
        missionText: "Sağlık hizmetlerine erişimi basitleştirmek, hasta ve doktor arasındaki iletişimi güçlendirmek ve en son teknolojiyi kullanarak herkes için daha sağlıklı bir gelecek inşa etmek.",
        visionTitle: "Vizyonumuz",
        visionText: "Türkiye'nin en yenilikçi ve en çok tercih edilen dijital sağlık platformu olmak; sağlık verilerinizi güvenli, erişilebilir ve anlamlı kılarak hayat kalitenizi artırmak.",
        featuresTitle: "Neden LUMINEX?",
        feature1Title: "Kolay Randevu",
        feature1Text: "Saniyeler içinde, dilediğiniz doktordan randevu alın.",
        feature2Title: "Anında Sonuçlar",
        feature2Text: "Tahlil ve görüntüleme sonuçlarınıza anında erişin.",
        feature3Title: "Güvenli İletişim",
        feature3Text: "Doktorunuzla güvenli ve özel bir şekilde mesajlaşın.",
        feature4Title: "Sağlık Geçmişi",
        feature4Text: "Tüm sağlık geçmişinizi tek bir yerde güvenle saklayın.",
        contactTitle: "Bize Ulaşın",
        contactInfoTitle: "İletişim Bilgileri",
        addressText: "Merkez Mah. Sağlık Sok. No:123, İstanbul",
        phoneText: "+90 (212) 555 00 00",
        emailText: "destek@luminex.com.tr",
        yourName: "Adınız",
        yourEmail: "E-posta Adresiniz",
        yourMessage: "Mesajınız",
        sendMessage: "Gönder",
        footerText: "2025 LUMINEX. Tüm hakları saklıdır.",
        registerTitle: "LUMINEX - Kayıt Ol",
        newBeginning: "Yeni Bir Başlangıç Yapın!",
        joinUs: "Sağlıklı bir yaşama adım atmak için şimdi bize katılın.",
        alreadyHaveAccount: "Zaten bir hesabınız var mı?",
        loginNow: "Şimdi Giriş Yap",
        fullName: "Tam Adınız",
        fullNamePlaceholder: "Tam adınızı girin",
        tcId: "T.C. Kimlik Numarası",
        tcIdPlaceholder: "T.C. Kimlik Numaranızı giriniz",
        email: "E-posta",
        emailPlaceholder: "E-posta adresinizi girin",
        phoneNumber: "Telefon Numarası",
        phonePlaceholder: "Telefon numaranızı girin",
        password: "Şifre",
        passwordPlaceholder: "Şifrenizi girin",
        passwordConfirm: "Şifre Tekrar",
        passwordConfirmPlaceholder: "Şifrenizi tekrar girin",
        passwordWeak: "Zayıf",
        passwordMedium: "Orta",
        passwordGood: "İyi",
        passwordStrong: "Güçlü",
        enterPassword: "Şifre girin",
        birthDate: "Doğum Tarihi",
        gender: "Cinsiyet (Opsiyonel)",
        select: "Seçiniz",
        male: "Erkek",
        female: "Kadın",
        other: "Diğer",
        termsLabel: "<a href='#' onclick='showTermsModal(event)' style='position: relative; z-index: 2000; text-decoration: underline; color: #3399FF;'>Kullanım Koşulları</a>'nı ve <a href='#' onclick='showKvkkModal(event)' style='position: relative; z-index: 2000; text-decoration: underline; color: #3399FF;'>KVKK Aydınlatma Metni</a>'ni okudum, onaylıyorum.",
        termsLink: "Kullanım Koşulları",
        kvkkLink: "KVKK Aydınlatma Metni",
        registerButton: "KAYIT OL",
        forgotPasswordTitle: "LUMINEX - Şifremi Unuttum",
        forgotPasswordHeader: "Şifrenizi mi unuttunuz?",
        forgotPasswordSubheader: "Endişelenmeyin! E-posta adresinizi girin, size şifre sıfırlama talimatlarını gönderelim.",
        backToLogin: "Giriş ekranına geri dönmek için ",
        clickHere: "tıklayın",
        firstName: "Ad",
        firstNamePlaceholder: "Adınızı girin",
        lastName: "Soyad",
        lastNamePlaceholder: "Soyadınızı girin",
        emailAddress: "E-posta Adresi",
        sendResetLink: "Şifre Sıfırlama Bağlantısı Gönder",
        welcomeBack: "Tekrar Hoş Geldiniz!",
        loginToYourAccount: "Hesabınıza giriş yapın",
        rememberMe: "Beni Hatırla",
        forgotPassword: "Şifrenizi mi unuttunuz?",
        dontHaveAccount: "Hesabınız yok mu?",
        createAccount: "Hesap Oluştur",
        usernameOrEmail: "Kullanıcı Adı veya E-posta",
        usernameOrEmailPlaceholder: "Kullanıcı adınızı veya e-posta adresinizi girin",
        niceToSeeYou: "Seni yeniden görmek harika! Lütfen giriş yap ve sağlığına bir adım daha yaklaş.",
        noAccount: "Hesabın yok mu?",
        registerNow: "Hemen Kayıt Olun",
        loginButton: "GİRİŞ YAP",
        kvkkTitle: "LUMINEX - KVKK Aydınlatma Metni",
        kvkkHeader: "🔐 KVKK AYDINLATMA METNİ",
        kvkkIntro: "LUMINEX olarak kişisel verilerinizi 6698 Sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında korumaktayız.",
        kvkkIntroText: "LUMINEX olarak kişisel verilerinizi 6698 Sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında korumaktayız.",
        dataControllerTitle: "Veri Sorumlusu",
        dataControllerName: "LUMINEX Sağlık Teknolojileri.",
        collectedDataTitle: "Toplanan Veriler",
        collectedDataDetails: "Ad-soyad, e-posta adresi, telefon numarası, doğum tarihi, cinsiyet, randevu geçmişi.",
        dataProcessingPurposeTitle: "Veri İşleme Amacı",
        purpose1: "Randevu işlemlerini yürütmek,",
        purpose2: "Hatırlatma ve bilgilendirme mesajları göndermek,",
        purpose3: "Hizmet kalitesini artırmak.",
        dataRetentionTitle: "Veri Saklama Süresi",
        dataRetentionDetails: "Yasal zorunluluklar ve hizmet sürekliliği kapsamında makul bir süre boyunca saklanır.",
        dataSharingTitle: "Veri Paylaşımı",
        dataSharingDetails: "Verileriniz üçüncü kişilerle paylaşılmaz; yalnızca gerekli yasal mercilerle paylaşılabilir.",
        yourRightsTitle: "Haklarınız",
        right1: "Kişisel verilerinize erişme,",
        right2: "Düzeltilmesini veya silinmesini isteme,",
        right3: "İşlemeyi reddetme haklarına sahipsiniz.",
        contactTitleKVKK: "İletişim",
        contactDetailsKVKK: "Talepleriniz için destek@luminex.com.tr adresinden bize ulaşabilirsiniz.",
        footerNoteKVKK: "🔒 LUMINEX, kişisel verilerinizi özenle korur ve gizliliğinizi her zaman ön planda tutar.",
        backToRegister: "Kayıt Ekranına Geri Dön",
        appointmentTitle: "Randevu Al",
        termsHeader: "KULLANIM ŞARTLARI",
        termsWelcome: "LUMINEX’e hoş geldiniz.",
        termsIntro: "Bu platform, kullanıcıların sağlık hizmetlerine kolay ve güvenli bir şekilde erişmesini sağlamak amacıyla tasarlanmıştır. Sistemi kullanarak aşağıdaki şartları kabul etmiş olursunuz:",
        term1: "LUMINEX, sunduğu randevu, bilgilendirme ve sağlık yönlendirme hizmetlerini geliştirme hakkını saklı tutar.",
        term2: "Kullanıcı, sisteme kayıt olurken verdiği bilgilerin doğru ve güncel olduğunu beyan eder.",
        term3: "LUMINEX üzerinde yapılan işlemler yalnızca bilgilendirme ve yönlendirme amaçlıdır; tıbbi tavsiye niteliği taşımaz.",
        term4: "Kullanıcı, hesabının güvenliğinden sorumludur. Şifresini üçüncü kişilerle paylaşmamalıdır.",
        term5: "LUMINEX, sistemde yapılan hatalı veya eksik bildirimlerden doğan zararlardan sorumlu tutulamaz.",
        term6: "Kullanıcı dilediği zaman hesabını silebilir, verilerini sistemden kaldırabilir.",
        term7: "Kullanım koşulları zaman zaman güncellenebilir; güncel versiyon her zaman bu alanda yer alacaktır.",
        termsFooterNote: "💡 Sistemi kullanmaya devam ettiğinizde, bu şartları kabul etmiş sayılırsınız.",
        // Privacy Policy
        privacyPolicyTitle: "Gizlilik Politikası",
        privacyIntro: "Gizliliğiniz bizim için önemlidir. Luminex platformunu kullanırken verilerinizin nasıl işlendiğini bu sayfada bulabilirsiniz.",
        privacySection1: "Veri Güvenliği",
        privacySection1Text: "Tüm verileriniz 256-bit SSL sertifikası ile şifrelenir ve güvenli sunucularda saklanır.",
        // Cookie Policy
        cookiePolicyTitle: "Çerez Politikası",
        cookieIntro: "Size daha iyi bir deneyim sunmak için çerezleri kullanıyoruz.",
        cookieSection1: "Çerez Kullanımı",
        cookieSection1Text: "Sistem, oturum yönetimi ve tercihlerinizi hatırlamak için zorunlu çerezler kullanır.",
        resetPasswordTitle: "LUMINEX - Şifre Sıfırla",
        resetPasswordHeader: "Şifrenizi Sıfırlayın",
        resetPasswordSubheader: "Lütfen hesabınızın güvenliği için yeni ve güçlü bir şifre belirleyin.",
        resetPasswordText: "Lütfen hesabınızın güvenliği için yeni ve güçlü bir şifre belirleyin.",
        backToLoginReset: "Giriş ekranına geri dönmek için ",
        resetPasswordFormTitle: "Şifre Sıfırla",
        newPasswordLabel: "Yeni Şifre",
        newPasswordPlaceholder: "Yeni şifrenizi girin",
        confirmNewPasswordLabel: "Yeni Şifreyi Onayla",
        confirmNewPasswordPlaceholder: "Yeni şifrenizi tekrar girin",
        updatePasswordButton: "Şifreyi Güncelle",
        dashboardTitle: "LUMINEX - Hasta Paneli",
        backToDashboardTitle: "Kontrol Paneline Dön",
        dashboardSidebar: "Kontrol Paneli",
        myAppointmentsSidebar: "Randevularım",
        doctorsBranchesSidebar: "Doktorlar / Branşlar",
        testResultsSidebar: "Tahlil & Sonuçlar",
        radiologyResultsSidebar: "Radyolojik Görüntülerim",
        prescriptionsSidebar: "Reçetelerim",
        healthHistorySidebar: "Sağlık Geçmişim",
        contactSupportSidebar: "İletişim / Destek",
        collapseMenu: "Menüyü Daralt",
        homePageHeader: "Ana Sayfa",
        notificationsTitle: "Bildirimler",
        all: "Tümü",
        unread: "Okunmamış",
        markAllAsRead: "Tümünü Okundu İşaretle",
        noUnreadNotifications: "Okunmamış bildiriminiz yok.",
        noNotificationsEver: "Henüz bildiriminiz bulunmuyor.",
        loginToSeeNotifications: "Bildirimlerinizi görmek için lütfen giriş yapın.",
        nextAppointmentHeader: "Sıradaki Randevunuza",
        bookAppointmentQuick: "Randevu Al",
        viewTestResultsQuick: "Tahlil Sonuçlarını Gör",
        myRadiologyImagesQuick: "Radyolojik Görüntülerim",
        doctorMessagesQuick: "Doktor Mesajları",
        doctorRatingQuick: "Doktor Değerlendirme",
        announcementsHealthTips: "Duyurular & Sağlık Önerileri",
        statisticsHeader: "İstatistikler",
        monthlyAppointmentsStats: "Bu ay 0 randevunu tamamladın.",
        adminDashboardTitle: "LUMINEX - Admin Paneli",
        adminWelcomeMessage: "Admin Paneline Hoş Geldiniz!", // Placeholder for dynamic name
        loadingText: "Yükleniyor...",
        secureSession: "Güvenli Oturum",
        totalUsersLabel: "Toplam Kullanıcı",
        lastWeekTrend: "Geçen haftaya göre",
        activeDoctorsLabel: "Aktif Doktor",
        newJoinersTrend: "Yeni katılanlar var",
        todayAppointmentsLabel: "Bugünkü Randevular",
        increaseYesterdayTrend: "Düne göre artış",
        partnerHospitalsLabel: "Anlaşmalı Hastane",
        stableTrend: "Stabil",
        appointmentActivityHeader: "Randevu Aktivitesi",
        thisWeekOption: "Bu Hafta",
        thisMonthOption: "Bu Ay",
        quickActionsHeader: "Hızlı İşlemler",
        addUserQuickAction: "Kullanıcı Ekle",
        addHospitalQuickAction: "Hastane Ekle",
        getReportQuickAction: "Rapor Al",
        refreshSystemQuickAction: "Sistemi Yenile",
        systemStatusHeader: "Sistem Durumu",
        databaseStatus: "Veritabanı",
        onlineStatus: "Çevrimiçi",
        apiServicesStatus: "API Servisleri",
        uptimeStatus: "%99.9 Uptime",
        backupStatus: "Yedekleme",
        pendingStatus: "Bekliyor",
        adminDashboardSidebar: "Kontrol Paneli",
        adminUsersSidebar: "Kullanıcılar",
        adminHospitalsSidebar: "Hastaneler",
        adminDepartmentsSidebar: "Departmanlar",
        adminReportsSidebar: "Raporlar",
        adminSupportRequestsSidebar: "Destek Talepleri",
        userExistsError: 'Bu T.C. Kimlik Numarası veya E-posta ile zaten bir kullanıcı kayıtlı.',
        registerSuccess: 'KAYIT BAŞARILI!',
        fullNameRequired: 'Ad Soyad boş bırakılamaz.',
        tcIdInvalid: 'Geçerli bir T.C. Kimlik Numarası girin.',
        emailInvalid: 'Geçerli bir e-posta adresi girin.',
        phoneInvalid: 'Geçerli bir telefon numarası girin (10 hane).',
        passwordInvalid: 'Şifre en az 8 karakter olmalı, büyük/küçük harf, sayı ve özel karakter içermelidir.',
        passwordMismatch: 'Şifreler eşleşmiyor.',
        ageInvalid: '18 yaşından büyük olmalısınız.',
        termsRequired: 'Kullanım koşulları ve KVKK metni onaylanmalıdır.',
        fieldRequired: 'Bu alan boş bırakılamaz.',
        loginToSeeReviews: "Değerlendirmelerinizi görmek için lütfen giriş yapın.",
        noReviewsFoundPlaceholder: "Henüz bir değerlendirme yapmadınız.",
        noReviewsFoundPlaceholderSubtext: "Tamamlanan randevularınızdan sonra doktorlarınızı değerlendirebilirsiniz.",
        deleteReview: "Sil",
        deleteReviewConfirm: "Emin misiniz?",
        deleteReviewConfirmMsg: "Bu değerlendirmeyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
        yesDelete: "Evet, Sil",
        cancel: "İptal",
        deleted: "Silindi!",
        reviewDeleted: "Değerlendirmeniz başarıyla silindi.",
        myReviewsTitle: "Değerlendirmelerim",
        myReviewsSidebar: "Değerlendirmelerim",
        kvkkPageTitle: "LUMINEX - KVKK Aydınlatma Metni",
        kvkkMainHeader: "🔐 KVKK AYDINLATMA METNİ",
        kvkkIntroText: "LUMINEX olarak kişisel verilerinizi 6698 Sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında korumaktayız.",
        dataController: "Veri Sorumlusu",
        dataControllerText: "LUMINEX Sağlık Teknolojileri.",
        collectedData: "Toplanan Veriler",
        collectedDataText: "Ad-soyad, e-posta adresi, telefon numarası, doğum tarihi, cinsiyet, randevu geçmişi.",
        processingPurpose: "Veri İşleme Amacı",
        purposeItem1: "Randevu işlemlerini yürütmek,",
        purposeItem2: "Hatırlatma ve bilgilendirme mesajları göndermek,",
        purposeItem3: "Hizmet kalitesini artırmak.",
        retentionPeriod: "Veri Saklama Süresi",
        retentionPeriodText: "Yasal zorunluluklar ve hizmet sürekliliği kapsamında makul bir süre boyunca saklanır.",
        dataSharing: "Veri Paylaşımı",
        dataSharingText: "Verileriniz üçüncü kişilerle paylaşılmaz; yalnızca gerekli yasal mercilerle paylaşılabilir.",
        userRights: "Haklarınız",
        rightsItem1: "Kişisel verilerinize erişme,",
        rightsItem2: "Düzeltilmesini veya silinmesini isteme,",
        rightsItem3: "İşlemeyi reddetme haklarına sahipsiniz.",
        kvkkContact: "İletişim",
        kvkkContactText: "Talepleriniz için destek@luminex.com.tr adresinden bize ulaşabilirsiniz.",
        kvkkFooter: "🔒 LUMINEX, kişisel verilerinizi özenle korur ve gizliliğinizi her zaman ön planda tutar.",
        termsPageTitle: "LUMINEX - Kullanım Şartları",
        termsMainHeader: "KULLANIM ŞARTLARI",
        termsWelcomeText: "LUMINEX’e hoş geldiniz.",
        termsIntroText: "Bu platform, kullanıcıların sağlık hizmetlerine kolay ve güvenli bir şekilde erişmesini sağlamak amacıyla tasarlanmıştır. Sistemi kullanarak aşağıdaki şartları kabul etmiş olursunuz:",
        termItem1: "LUMINEX, sunduğu randevu, bilgilendirme ve sağlık yönlendirme hizmetlerini geliştirme hakkını saklı tutar.",
        termItem2: "Kullanıcı, sisteme kayıt olurken verdiği bilgilerin doğru ve güncel olduğunu beyan eder.",
        termItem3: "LUMINEX üzerinde yapılan işlemler yalnızca bilgilendirme ve yönlendirme amaçlıdır; tıbbi tavsiye niteliği taşımaz.",
        termItem4: "Kullanıcı, hesabının güvenliğinden sorumludur. Şifresini üçüncü kişilerle paylaşmamalıdır.",
        termItem5: "LUMINEX, sistemde yapılan hatalı veya eksik bildirimlerden doğan zararlardan sorumlu tutulamaz.",
        termItem6: "Kullanıcı dilediği zaman hesabını silebilir, verilerini sistemden kaldırabilir.",
        termItem7: "Kullanım koşulları zaman zaman güncellenebilir; güncel versiyon her zaman bu alanda yer alacaktır.",
        termsFooter: "💡 Sistemi kullanmaya devam ettiğinizde, bu şartları kabul etmiş sayılırsınız.",
        backToRegisterBtn: "Kayıt Ekranına Geri Dön",
        backToHome: "Ana Sayfaya Dön",
        readAndUnderstood: "Okudum, Anladım",
        errorTitle: "Hata",
        contentLoadError: "İçerik yüklenemedi.",
        tcRequired: "T.C. Kimlik Numarası boş bırakılamaz.",
        passwordRequired: "Şifre boş bırakılamaz.",
        ageRestriction: "18 yaşından küçükler giriş yapamaz.",
        passwordIncorrect: "Girdiğiniz şifre yanlış. Lütfen tekrar deneyin.",
        userNotFound: "Bu T.C. Kimlik Numarası ile kayıtlı bir kullanıcı bulunamadı.",
        tooManyAttempts: "Çok fazla hatalı deneme. Lütfen {seconds} saniye sonra tekrar deneyin.",
        accountTemporarilyLocked: "Hesabınız geçici olarak kilitlenmiştir.",
        attemptsRemaining: "({attempts} deneme hakkınız kaldı)",
        forgotTcInvalid: "Lütfen geçerli bir 11 haneli T.C. Kimlik Numarası girin.",
        forgotFirstNameRequired: "Lütfen adınızı girin.",
        forgotLastNameRequired: "Lütfen soyadınızı girin.",
        forgotEmailInvalid: "Lütfen geçerli bir e-posta adresi girin.",
        checkingInfo: "Bilgileriniz kontrol ediliyor...",
        infoVerifiedRedirecting: "Bilgiler doğrulandı! Yönlendiriliyorsunuz...",
        userNotFoundForgot: "Hata: Girdiğiniz bilgilerle eşleşen bir kullanıcı bulunamadı.",
        editReview: "Düzenle",
        editYourReview: "Değerlendirmenizi Düzenleyin",
        saveChanges: "Değişiklikleri Kaydet",
        reviewUpdated: "Değerlendirmeniz başarıyla güncellendi.",
        invalidOrMissingResetToken: "Geçersiz veya eksik sıfırlama anahtarı. Lütfen şifre sıfırlama işlemini yeniden başlatın.",
        enterNewPassword: "Lütfen yeni şifrenizi girin.",
        confirmNewPassword: "Lütfen yeni şifrenizi onaylayın.",
        passwordsDoNotMatch: "Şifreler eşleşmiyor.",
        passwordUpdateSuccess: "Şifreniz başarıyla güncellendi. Giriş sayfasına yönlendiriliyorsunuz...",
        invalidOrExpiredToken: "Sıfırlama anahtarı geçersiz veya süresi dolmuş.",
        codeSentMessage: "Doğrulama kodu e-posta adresinize gönderildi.",
        enterVerificationCode: "Doğrulama Kodunu Girin",
        verifyCodeButton: "Kodu Doğrula",
        invalidCode: "Girdiğiniz doğrulama kodu geçersiz.",
        searchNotifications: "Bildirimlerde ara...",
        allCategories: "Tüm Kategoriler",
        categoryAppointment: "Randevular",
        categoryTestResult: "Tahlil Sonuçları",
        categoryAlert: "Uyarılar",
        categorySystem: "Sistem",
        allNotifications: "Tüm Bildirimler",
        noNotificationsFound: "Aradığınız kriterlere uygun bildirim bulunamadı.",
        markAsRead: "Okundu İşaretle",
        alreadyRead: "Okundu",
        today: "Bugün",
        yesterday: "Dün",
        contactHeroTitle: "Size Nasıl Yardımcı Olabiliriz?",
        contactHeroSubtitle: "Luminex destek ekibi olarak her zaman yanınızdayız.",
        callUs: "Bizi Arayın",
        callUsDesc: "Hafta içi 09:00 - 18:00 saatleri arasında ulaşabilirsiniz.",
        emailUs: "E-posta Gönderin",
        emailUsDesc: "Tüm sorularınız için 7/24 bize yazabilirsiniz.",
        visitUs: "Ziyaret Edin",
        visitUsDesc: "Merkez ofisimizde sizi ağırlamaktan mutluluk duyarız.",
        showOnMap: "Haritada Gör",
        sendTicket: "Destek Talebi Oluşturun",
        selectSubject: "Konu seçin...",
        enterMessageDetails: "Lütfen mesajınızı detaylıca açıklayın...",
        ourLocation: "Konumumuz",
        faqTitle: "Sıkça Sorulan Sorular",
        // FAQ - Short keys (for HTML)
        faq1Q: "Luminex'i mevcut hastane sistemime (HBYS) entegre edebilir miyim?",
        faq1A: "Evet, Luminex HL7 ve FHIR standartlarını destekler. Mevcut HBYS yazılımınızla %100 uyumlu çalışarak veri kaybı olmadan çift yönlü entegrasyon sağlar.",
        faq2Q: "Veri güvenliği ve KVKK uyumluluğu nasıl sağlanıyor?",
        faq2A: "Tüm verileriniz 256-bit SSL ile şifrelenir ve Türkiye'deki Tier-3 veri merkezlerinde saklanır. Sistemimiz KVKK ve GDPR standartlarına tam uyumludur.",
        faq3Q: "Kurulum ve eğitim süreci ne kadar sürüyor?",
        faq3A: "Bulut tabanlı yapımız sayesinde kurulum gerekmez. Hesabınız 24 saat içinde aktif edilir ve personeliniz için 2 günlük online eğitim programımız ücretsizdir.",
        faq4Q: "Teknik destek hizmetiniz neleri kapsıyor?",
        faq4A: "Tüm paketlerimizde 7/24 e-posta desteği standarttır. Kurumsal paketlerde ise size özel atanan müşteri temsilcisi ile telefonla 7/24 destek alabilirsiniz.",
        // FAQ - Long keys (existing)
        faq1Question: "LUMINEX ücretli mi?",
        faq1Answer: "Hayır, hastalar için randevu almak, sonuçları görüntülemek ve temel özellikleri kullanmak tamamen ücretsizdir.",
        faq2Question: "Verilerim güvende mi?",
        faq2Answer: "Kesinlikle. Verileriniz en son şifreleme teknolojileri ile korunur ve sadece sizin izninizle doktorlarınızla paylaşılır.",
        faq3Question: "Nasıl randevu alabilirim?",
        faq3Answer: "Ücretsiz kayıt olduktan sonra doktorları branşa veya isme göre arayabilir, uygun saatleri görüp tek tıkla randevu alabilirsiniz.",
        faq4Question: "Tahlil sonuçlarımı nasıl görebilirim?",
        faq4Answer: "Profilinize giriş yaptıktan sonra \"Sağlık Geçmişim\" bölümünden tüm laboratuvar ve radyoloji sonuçlarınıza anında erişebilirsiniz.",
        faq5Question: "Luminex'i mevcut hastane sistemime (HBYS) entegre edebilir miyim?",
        faq5Answer: "Evet, Luminex esnek yapısı sayesinde mevcut hastane bilgi yönetim sistemlerinize (HBYS) kolayca entegre edilebilir. Detaylar için entegrasyon ekibimizle iletişime geçebilirsiniz.",
        faq6Question: "Kurulum ve eğitim süreci ne kadar sürüyor?",
        faq6Answer: "Kurulum süreci hastanenizin büyüklüğüne ve entegrasyon gereksinimlerine göre değişmekle birlikte, genellikle 2-4 hafta içinde tamamlanır. Eğitimler de bu süreçte entegre bir şekilde yürütülür.",
        faq7Question: "Teknik destek hizmetiniz neleri kapsıyor?",
        faq7Answer: "7/24 kesintisiz teknik destek, yazılım güncellemeleri, periyodik bakım, performans optimizasyonu ve uzaktan yardım hizmetlerini kapsarız.",
        filter: "Filtrele",
        searchByDoctorName: "Doktor adı ile ara...",
        searchByBranch: "Kardiyoloji, Dahiliye...",
        starRating: "Yıldız Puanı",
        allRatings: "Tüm Puanlar",
        fourStarsAbove: "4 Yıldız ve Üzeri",
        threeStarsAbove: "3 Yıldız ve Üzeri",
        twoStarsAbove: "2 Yıldız ve Üzeri",
        oneStarAbove: "1 Yıldız ve Üzeri",
        doctorList: "Doktor Listesi",
        allBranches: "Tüm Branşlar",
        noDoctorsFound: "Aradığınız kriterlere uygun doktor bulunamadı.",
        reviewsCount: "{count} değerlendirme",
        readReviews: "Yorumları Oku",
        reviewsNotFoundTitle: "Yorum Bulunamadı",
        reviewsNotFoundText: "{name} için henüz bir değerlendirme yapılmamış.",
        averageRatingLabel: "Ortalama Puan",
        pendingTickets: "Bekleyen Talepler",
        statusOpen: "Açık",
        statusClosed: "Closed",
        startDate: "Başlangıç Tarihi",
        endDate: "Bitiş Tarihi",
        testName: "Test Adı",
        searchByTestName: "Kan, idrar...",
        outOfRangeOnly: "Sadece Referans Dışı",
        applyFilters: "Filtrele",
        clear: "Temizle",
        noResultsFound: "Bu kriterlere uygun sonuç bulunmamaktadır.",
        tryChangingFilters: "Filtrelerinizi değiştirmeyi veya temizlemeyi deneyin.",
        dateLabel: "Tarih",
        doctorLabel: "Doktor",
        viewDetails: "Detayları Görüntüle",
        downloadPdf: "PDF İndir",
        outOfRangeValuesPresent: "(Referans Dışı Değerler Mevcut)",
        referenceLabel: "Referans",
        outOfRangeWarning: "Sonuç referans aralığı dışında",
        inRangeInfo: "Sonuç referans aralığında",
        ok: "Anladım",
        confirmTitle: "Onay",
        openReportInNewTab: "Rapor sayfası yeni bir sekmede açılacaktır. Onaylıyor musunuz?",
        yesOpen: "Evet, Aç!",
        imagingType: "Görüntüleme Türü",
        searchByImagingType: "MR, Röntgen...",
        viewReport: "Raporu Görüntüle",
        openImages: "Görüntüleri Aç",
        technique: "Teknik",
        findings: "Bulgular",
        resultComment: "Sonuç / Yorum",
        noInfo: "Bilgi yok.",
        close: "Kapat",
        eventType: "Olay Türü",
        appointmentEvent: "Poliklinik Randevusu",
        testEvent: "Tahlil Sonucu",
        prescriptionEvent: "Reçete",
        radiologyEvent: "Radyoloji Sonucu",
        testTitle: "Tahlil Sonucu",
        prescriptionTitle: "Reçete",
        radiologyTitle: "Röntgen Sonucu",
        noHealthHistoryFound: "Gösterilecek sağlık geçmişi kaydı bulunamadı.",
        diagnosisLabel: "Tanı",
        details: "Detaylar",
        statusUpcoming: "Yaklaşan",
        statusPast: "Geçmiş",
        statusCancelled: "İptal Edildi",
        statusWaiting: "Bekliyor",
        statusApproved: "Onaylandı",
        noAppointmentsFound: "Görüntülenecek randevu bulunmamaktadır.",
        cancelAppointment: "İptal Et",
        evaluate: "Değerlendir",
        reschedule: "Yeniden Planla",
        healthInfo: "Sağlık Bilgisi",
        prescriptionDetail: "Reçete Detayı",
        unspecifiedDiagnosis: "Tanı Belirtilmemiş",
        prescriptionDetailsTitle: "Reçete Detayları",
        preparing: "Hazırlanıyor...",
        preparingDesc: "Reçete belgesi oluşturuluyor",
        dosage: "Dozaj",
        doctorNameLabel: "Doktor Adı",
        statusLabel: "Durum",
        myself: "Kendim",
        locationInfo: "Konum Bilgileri",
        provinceSelection: "İl Seçimi",
        typeOrSelectProvince: "İl yazın veya seçin...",
        districtSelection: "İlçe Seçimi",
        selectProvinceFirst: "Önce İl Seçiniz",
        hospitalSelection: "Hastane Seçimi",
        selectDistrictFirst: "Önce İlçe Seçiniz",
        appointmentDetails: "Randevu Detayları",
        branchSelection: "Branş Seçimi",
        typeOrSelectBranch: "Branş yazın veya seçin...",
        doctorSelection: "Doktor Seçimi",
        selectHospitalAndBranch: "Hastane ve Branş Seçiniz",
        appointmentPerson: "Randevu Alan Kişi",
        dateSelection: "Tarih Seçimi",
        availableHours: "Müsait Saatler",
        selectDateFirst: "Lütfen tarih seçimi yapınız.",
        importantHealthInfo: "Önemli Sağlık Bilgisi",
        enterHealthInfoPlaceholder: "Önemli sağlık bilgilerinizi buraya yazabilirsiniz...",
        appointmentSummary: "Randevu Özeti",
        timeLabel: "Saat",
        notSelected: "Seçilmedi",
        notEntered: "Girilmedi",
        confirmAppointment: "Randevuyu Onayla",
        // Branches
        cardiology: "Kardiyoloji",
        internalMedicine: "Dahiliye",
        orthopedics: "Ortopedi",
        ophthalmology: "Göz Hastalıkları",
        pediatrics: "Çocuk Sağlığı ve Hastalıkları",
        generalSurgery: "Genel Cerrahi",
        gynecology: "Kadın Hastalıkları ve Doğum",
        otolaryngology: "Kulak Burun Boğaz",
        neurology: "Nöroloji",
        psychiatry: "Psikiyatri",
        urology: "Üroloji",
        physicalTherapy: "Fizik Tedavi ve Rehabilitasyon",
        dermatology: "Dermatoloji",
        pulmonology: "Göğüs Hastalıkları",
        infection: "Enfeksiyon Hastalıkları",
        gastroenterology: "Gastroenteroloji",
        endocrinology: "Endokrinoloji",
        rheumatology: "Romatoloji",
        nephrology: "Nefroloji",
        oncology: "Onkoloji",
        anesthesiology: "Anesteziyoloji ve Reanimasyon",
        // Dashboard Widgets
        sunny: "Güneşli",
        sunnyTip: "Güneşli hava! D vitamini depolamak için harika bir gün.",
        cloudy: "Parçalı Bulutlu",
        cloudyTip: "Hava biraz serin olabilir, yürüyüş yaparken hafif giyin.",
        rainy: "Yağmurlu",
        rainyTip: "Yağmur berekettir! Dışarı çıkacaksan şemsiyeni unutma.",
        medicineSuccessTitle: "Harika!",
        medicineSuccessText: "İlaç takibiniz başarıyla kaydedildi.",
        medicineTaken: "Alındı ✓",
        monthlyAppointmentsStats: "Bu ay {count} randevunu tamamladın.",
        countdownDays: "Gün",
        countdownHours: "Sa",
        countdownMinsRemaining: "Dk kaldı",
        countdownHeaderPrefix: "Randevunuza:",
        examination: "Muayene",
        waiting: "Bekleniyor",
        completed: "Tamamlandı",
        confirmCancelTitle: "Emin misiniz?",
        confirmCancelText: "Bu randevuyu iptal etmek istediğinizden emin misiniz?",
        yesCancel: "Evet, iptal et!",
        noStay: "Hayır",
        cancelledTitle: "İptal Edildi!",
        cancelledText: "Randevunuz başarıyla iptal edildi.",
        noHealthRecords: "Henüz bir sağlık kaydı bulunmuyor.",
        // Health Tips
        tip_water: "Günde en az 8 bardak su için, vücudunuzu ve zihninizi canlı tutun.",
        tip_exercise: "Düzenli egzersiz yapmak kalp sağlığınızı iyileştirir ve stresi azaltır.",
        tip_flu: "Grip mevsimi yaklaşıyor, aşı olmayı ve kalabalık ortamlarda maske takmayı unutmayın.",
        tip_sleep: "Yeterli uyku almak bağışıklık sisteminizi güçlendirir ve enerjinizi artırır.",
        tip_diet: "Dengeli beslenin: Bol miktarda meyve, sebze ve tam tahıllı gıdalar tüketin.",
        tip_new_doc: "Yeni Kardiyoloji uzmanımız Dr. Emre Aksoy hasta kabulüne başlamıştır.",
        tip_sunscreen: "Güneş kremi kullanmak cilt kanseri riskini azaltır ve cildinizi korur.",
        tip_stress: "Stresi yönetmek için meditasyon veya derin nefes egzersizlerini deneyin.",
        tip_walking: "Her gün 30 dakika yürüyüş yapmak genel sağlığınız için harikalar yaratır.",
        tip_parking: "Hastanemizde devam eden inşaat çalışmaları nedeniyle otoparkta yoğunluk yaşanabilir.",
        tip_breakfast: "Kahvaltıyı atlamayın, günün en önemli öğünüdür.",
        tip_smoke_alcohol: "Sigara ve alkolden uzak durmak uzun ve sağlıklı bir yaşam için kritik öneme sahiptir.",
        tip_appointment_system: "Online randevu sistemimiz yenilendi! Artık daha hızlı ve kolay randevu alabilirsiniz.",
        tip_checkup: "Düzenli doktor kontrollerinizi aksatmayın, erken teşhis hayat kurtarır.",
        // Notification Messages - Patient
        notif_p_1_msg: "Yarın saat 14:30'da Kardiyoloji Polikliniği'nde Dr. Ayşe Yılmaz ile randevunuz bulunmaktadır.",
        notif_p_2_msg: "Son yaptırdığınız Kan Tahlili sonuçlarınız çıkmıştır. Sonuçlarım sayfasından inceleyebilirsiniz.",
        notif_p_3_msg: "İlaç Hatırlatması: \"Parol\" ilacınızı tok karnına almayı unutmayınız.",
        notif_p_4_msg: "Luminex Mobil Uygulamamız güncellendi! Yeni özellikleri keşfetmek için marketten indirebilirsiniz.",
        notif_p_5_msg: "Göz Hastalıkları randevunuz talebiniz üzerine başarıyla iptal edilmiştir.",
        notif_p_6_msg: "Sağlıklı Yaşam Kulübü: Bu ayki \"Diyabet ve Beslenme\" seminerine davetlisiniz.",
        // Notification Messages - Admin
        notif_a_1_msg: "Yeni bir kullanıcı kaydı yapıldı: Mehmet Yılmaz. Onay bekliyor.",
        notif_a_2_msg: "Sunucu Disk alanı %80 doluluğa ulaştı. Kontrol edilmesi gerekiyor.",
        notif_a_3_msg: "Bugün için toplam 15 yeni randevu oluşturuldu.",
        notif_a_4_msg: "Sistem yedekleme işlemi başarıyla tamamlandı.",
        notif_a_5_msg: "Son 24 saatte 3 başarısız yönetici giriş denemesi tespit edildi.",
        notif_a_6_msg: "Yeni bir hastane kaydı incelenmeyi bekliyor: Özel ABC Hastanesi.",
        // Index Page - Stats & Testimonials
        statsTitle: "Rakamlarla LUMINEX",
        happyPatients: "Mutlu Hasta",
        specialistDoctors: "Uzman Doktor",
        partnerHospitals: "Anlaşmalı Hastane",
        support247: "7/24 Destek",
        testimonialsTitle: "Hastalarımız Ne Diyor?",
        testimonial1Text: '"Randevu almak hiç bu kadar kolay olmamıştı. Tahlil sonuçlarımı evimden anında görüntüleyebiliyorum. Harika bir sistem!"',
        testimonial1Author: "Ayşe Yılmaz",
        patientLabel: "Hasta",
        testimonial2Text: '"Doktorumla iletişim kurabilmek benim için çok önemliydi. Luminex sayesinde aklımdaki soruları anında sorabiliyorum."',
        testimonial2Author: "Mehmet Kaya",
        testimonial3Text: '"Tüm sağlık geçmişimin tek bir yerde olması büyük kolaylık. Hangi doktora gidersem gideyim bilgilerim yanımda."',
        testimonial3Author: "Zeynep Erdem",
        // Footer
        footerCompanyDesc: "Sağlık teknolojilerinde yenilikçi çözümler sunan, hasta ve doktor arasındaki köprüyü dijital dünyada kuran güvenilir sağlık platformu.",
        corporateInfoTitle: "Kurumsal Bilgilerimiz:",
        mersisNoLabel: "MERSİS No:",
        tradeRegistryNoLabel: "Ticari Sicil No:",
        taxNoLabel: "Vergi No:",
        contactHours: "Hafta içi: 09:00 - 18:00",
        contactEmailSupport: "7/24 E-posta Desteği",
        contactAddressLine1: "Luminex Plaza, Şişli",
        contactAddressLine2: "İstanbul, Türkiye",
        quickLinksTitle: "Hızlı Bağlantılar",
        home: "Anasayfa",
        loginRegisterLink: "Giriş Yap / Kayıt Ol",
        trustSSL: "256-Bit SSL",
        trustSecure: "Güvenli Altyapı",
        trustVerified: "Onaylı Platform",
        trustEtbis: "ETBİS Kayıtlı",
        footerCopyright: "© 2025 LUMINEX Sağlık Teknolojileri A.Ş. Tüm hakları saklıdır.",
        privacyPolicy: "Gizlilik Politikası",
        termsOfUse: "Kullanım Şartları",
        cookiePolicy: "Çerez Politikası",
        // B2B / Corporate
        corporate: "Kurumsal",
        forClinics: "Klinikler İçin",
        solutionsTitle: "Klinik Yönetiminde Yeni Nesil Çözümler",
        solutionsSubtitle: "Luminex'i kendi kliniğinizde kullanın, verimliliğinizi %40 artırın.",
        b2bFeature1Title: "AI Destekli Triyaj",
        b2bFeature1Text: "Hastalarınız yanlış bölüme randevu almaz, doktorlarınızın vakti boşa gitmez.",
        b2bFeature2Title: "White-Label Tasarım",
        b2bFeature2Text: "Kendi logonuz ve renklerinizle kliniğinize özel bir deneyim sunun.",
        b2bFeature3Title: "Gelişmiş Analitik",
        b2bFeature3Text: "Hangi branşın ne kadar yoğun olduğunu ve hasta memnuniyetini anlık takip edin.",
        demoRequest: "Demo Talep Et",
        corporateContactTitle: "Luminex'i Kliniğinize Taşıyın",
        corporateContactDesc: "Hemen bir demo randevusu oluşturun ve dijital dönüşümünüzü başlatalım.",
        // Pricing
        pricingTitle: "Klinikler İçin Esnek Planlar",
        pricingSubtitle: "İhtiyacınıza en uygun paketi seçin, dijitalleşmeye bugün başlayın.",
        planBasic: "Başlangıç",
        planStandard: "Profesyonel",
        planPremium: "Kurumsal",
        planSubtitlePro: "Başlangıç paketine ek olarak",
        planSubtitleEnt: "Profesyonel pakete ek olarak",
        featAppointment: "Online Randevu Sistemi",
        featPatients: "Sınırsız Hasta Kaydı",
        featSMS: "SMS Bildirimleri (500 Adet)",
        featAI: "AI Destekli Triyaj",
        featWhiteLabel: "White-Label Tasarım",
        featAnalysis: "Gelişmiş Raporlama",
        featLab: "Laboratuvar Entegrasyonu",
        featFull: "Tüm Özellikler Sınırsız",
        featSupport: "7/24 Öncelikli Teknik Destek",
        featCustom: "Özel API Erişimi",
        selectPlan: "Hemen Başla",
        // Contact Form Specific
        warningTitle: "Uyarı",
        missingInfoTitle: "Eksik Bilgi", 
        fillAllFields: "Lütfen tüm alanları doldurduğunuzdan emin olun.",
        contactSuccessTitle: "Harika!",
        contactSuccessText: "Mesajınız başarıyla iletildi. En kısa sürede size geri dönüş yapacağız.",
        sendingMessage: "Gönderiliyor...",
        sendingTitle: "Gönderiliyor...",
        sendingText: "Mesajınız gönderiliyor, lütfen bekleyiniz.",
        genericErrorTitle: "Hata!",
        genericErrorMessageServer: "Sunucuda bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.",
        genericErrorMessageNetwork: "Bir ağ hatası oluştu. Lütfen internet bağlantınızı kontrol edip tekrar deneyiniz.",
        okButton: "Tamam",
        // B2B Contact Form
        yourPosition: "Pozisyon",
        yourPhone: "Telefon",
        companyName: "Klinik / Hastane Adı",
        branchCount: "Branş Sayısı",
        dailyPatients: "Günlük Hasta Sayısı",
        requestType: "Talep Türü",
        kvkkRequired: "KVKK Aydınlatma Metni'ni onaylamanız gerekmektedir.",
        // Form Section Headers
        personalInfo: "Kişisel Bilgiler",
        corporateInfo: "Kurumsal Bilgiler",
        contactInfo: "İletişim Bilgileri",
        requestDetails: "Talep Detayları",
        // Placeholders
        namePlaceholder: "Adınız Soyadınız",
        emailPlaceholder: "ornek@klinik.com",
        phonePlaceholder: "05XX XXX XX XX",
        companyPlaceholder: "Klinik veya hastanenizin adı",
        messagePlaceholder: "Talebinizi detaylıca açıklayın...",
        // Select Options
        selectOption: "Seçiniz",
        positionOwner: "Klinik Sahibi",
        positionManager: "Klinik Müdürü",
        positionDoctor: "Doktor",
        positionExecutive: "Yönetici",
        positionEmployee: "Çalışan",
        positionOther: "Diğer",
        branches1to5: "1-5 Branş",
        branches6to10: "6-10 Branş",
        branches11to20: "11-20 Branş",
        branches20plus: "20+ Branş",
        patientsLess50: "50'den az",
        patients50to100: "50-100",
        patients100to200: "100-200",
        patients200plus: "200+",
        requestDemo: "Demo Talebi",
        requestPricing: "Fiyat Bilgisi",
        requestTechnical: "Teknik Sorular",
        requestIntegration: "Entegrasyon Bilgisi",
        requestOther: "Diğer",
        // Contact Info Labels
        addressLabel: "Adres",
        phoneLabel: "Telefon",
        emailLabel: "E-posta",
        addressText: "Merkez Mah. Sağlık Sok. No:123, İstanbul",
        phoneText: "+90 (212) 555 00 00",
        emailText: "destek@luminex.com.tr",
        // KVKK
        kvkkApproveText: "<a href=\"kvkk.html?lang=tr\" style=\"color: var(--accent-color);\" data-lang=\"kvkkLinkText\">KVKK Aydınlatma Metni</a>'ni okudum, onaylıyorum. *",
        kvkkLinkText: "KVKK Aydınlatma Metni"
    },
    en: {
        about: "About Us",
        features: "Features",
        contact: "Contact",
        login: "Login",
        loginTitle: "LUMINEX - Login",
        heroTitle: "Digital Transformation in Health",
        heroSubtitle: "Access healthcare services with a single click. Plan your appointments, view your results.",
        cardAppointmentTitle: "Book Appointment",
        cardAppointmentDesc: "Easily create an appointment by selecting a hospital and physician.",
        cardResultsTitle: "Test Results",
        cardResultsDesc: "Access your laboratory and imaging results instantly.",
        cardDoctorsTitle: "Find a Doctor",
        cardDoctorsDesc: "Examine our expert physician staff and get information.",
        cardSymptomTitle: "Symptom Checker",
        cardSymptomDesc: "AI-supported preliminary diagnosis based on your complaints.",
        servicesTitle: "Online Services",
        servicePrescriptions: "My Prescriptions",
        serviceRadiology: "Radiology Images",
        serviceReports: "My Reports",
        serviceVisits: "My Visits",
        serviceEmergency: "Emergency",
        serviceSupport: "Live Support",
        featuredDoctorsTitle: "Featured Doctors",
        featuredDoctorsSubtitle: "We are with you with our expert staff.",
        register: "Sign Up for Free",
        aboutTitle: "Modern Healthcare Experience",
        aboutText: "Luminex combines traditional healthcare services with the speed and convenience of the digital world. We offer a platform that saves you time, reduces stress, and makes managing your health easier.",
        missionTitle: "Our Mission",
        missionText: "To simplify access to healthcare services, strengthen communication between patients and doctors, and build a healthier future for everyone by using the latest technology.",
        visionTitle: "Our Vision",
        visionText: "To be Turkey's most innovative and preferred digital health platform; enhancing your quality of life by making your health data secure, accessible, and meaningful.",
        featuresTitle: "Why LUMINEX?",
        feature1Title: "Easy Appointment",
        feature1Text: "Book an appointment with your preferred doctor in seconds.",
        feature2Title: "Instant Results",
        feature2Text: "Access your laboratory and imaging results instantly.",
        feature3Title: "Secure Messaging",
        feature3Text: "Message your doctor securely and privately.",
        feature4Title: "Health History",
        feature4Text: "Securely store your entire health history in one place.",
        contactTitle: "Contact Us",
        contactInfoTitle: "Contact Info",
        addressText: "Merkez Mah. Saglik Sok. No:123, Istanbul",
        phoneText: "+90 (212) 555 00 00",
        emailText: "destek@luminex.com.tr",
        yourName: "Your Name",
        yourEmail: "Your Email Address",
        yourMessage: "Your Message",
        sendMessage: "Send",
        footerText: "2025 LUMINEX. All rights reserved.",
        registerTitle: "LUMINEX - Register",
        newBeginning: "Make a New Start!",
        joinUs: "Join us now to step into a healthier life.",
        alreadyHaveAccount: "Already have an account?",
        loginNow: "Login Now",
        fullName: "Full Name",
        fullNamePlaceholder: "Enter your full name",
        tcId: "National ID Number",
        tcIdPlaceholder: "Enter your 11-digit National ID",
        email: "Email",
        emailPlaceholder: "Enter your email address",
        phoneNumber: "Phone Number",
        phonePlaceholder: "Enter your phone number",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        passwordConfirm: "Confirm Password",
        passwordConfirmPlaceholder: "Re-enter your password",
        passwordWeak: "Weak",
        passwordMedium: "Medium",
        passwordGood: "Good",
        passwordStrong: "Strong",
        enterPassword: "Enter password",
        birthDate: "Birth Date",
        gender: "Gender (Optional)",
        select: "Select",
        male: "Male",
        female: "Female",
        other: "Other",
        termsLabel: "I have read and approve the <a href='#' onclick='showTermsModal(event)' style='position: relative; z-index: 2000; text-decoration: underline; color: #3399FF;'>Terms of Use</a> and <a href='#' onclick='showKvkkModal(event)' style='position: relative; z-index: 2000; text-decoration: underline; color: #3399FF;'>KVKK Clarification Text</a>.",
        termsLink: "Terms of Use",
        kvkkLink: "KVKK Clarification Text",
        registerButton: "SIGN UP",
        forgotPasswordTitle: "LUMINEX - Forgot Password",
        forgotPasswordHeader: "Forgot your password?",
        forgotPasswordSubheader: "Don't worry! Enter your email address and we'll send you password reset instructions.",
        backToLogin: "To return to the login screen ",
        clickHere: "click here",
        firstName: "First Name",
        firstNamePlaceholder: "Enter your first name",
        lastName: "Last Name",
        lastNamePlaceholder: "Enter your last name",
        emailAddress: "Email Address",
        sendResetLink: "Send Password Reset Link",
        welcomeBack: "Welcome Back!",
        loginToYourAccount: "Login to your account",
        rememberMe: "Remember Me",
        forgotPassword: "Forgot your password?",
        dontHaveAccount: "Don't have an account?",
        createAccount: "Create Account",
        usernameOrEmail: "Username or Email",
        usernameOrEmailPlaceholder: "Enter your username or email address",
        niceToSeeYou: "Great to see you again! Please login and get one step closer to your health.",
        noAccount: "Don't have an account?",
        registerNow: "Register Now",
        loginButton: "LOGIN",
        kvkkTitle: "LUMINEX - KVKK Clarification Text",
        kvkkHeader: "🔐 KVKK CLARIFICATION TEXT",
        kvkkIntro: "As LUMINEX, we protect your personal data within the scope of the Personal Data Protection Law No. 6698 (“KVKK”).",
        kvkkIntroText: "As LUMINEX, we protect your personal data within the scope of the Personal Data Protection Law No. 6698 (“KVKK”).",
        dataControllerTitle: "Data Controller",
        dataControllerName: "LUMINEX Health Technologies.",
        collectedDataTitle: "Collected Data",
        collectedDataDetails: "Name-surname, email address, phone number, birth date, gender, appointment history.",
        dataProcessingPurposeTitle: "Data Processing Purpose",
        purpose1: "To conduct appointment processes,",
        purpose2: "To send reminder and information messages,",
        purpose3: "To improve service quality.",
        dataRetentionTitle: "Data Retention Period",
        dataRetentionDetails: "Stored for a reasonable period within the scope of legal obligations and service continuity.",
        dataSharingTitle: "Data Sharing",
        dataSharingDetails: "Your data is not shared with third parties; it can only be shared with necessary legal authorities.",
        yourRightsTitle: "Your Rights",
        right1: "To access your personal data,",
        right2: "To request correction or deletion,",
        right3: "You have the right to object to processing.",
        contactTitleKVKK: "Contact",
        contactDetailsKVKK: "You can reach us at destek@luminex.com.tr for your requests.",
        footerNoteKVKK: "🔒 LUMINEX protects your personal data with care and always prioritizes your privacy.",
        backToRegister: "Back to Register Screen",
        appointmentTitle: "Book Appointment",
        termsHeader: "TERMS OF USE",
        termsWelcome: "Welcome to LUMINEX.",
        termsIntro: "This platform is designed to provide users with easy and secure access to healthcare services. By using the system, you agree to the following terms:",
        term1: "LUMINEX reserves the right to improve the appointment, information, and health guidance services it offers.",
        term2: "The user declares that the information provided when registering for the system is correct and up-to-date.",
        term3: "Transactions made on LUMINEX are for information and guidance purposes only; they do not constitute medical advice.",
        term4: "The user is responsible for the security of their account. They should not share their password with third parties.",
        term5: "LUMINEX cannot be held responsible for damages arising from incorrect or incomplete notifications made in the system.",
        term6: "The user can delete their account and remove their data from the system at any time.",
        term7: "Terms of use may be updated from time to time; the current version will always be available in this area.",
        termsFooterNote: "💡 By continuing to use the system, you are deemed to have accepted these terms.",
        // Privacy Policy
        privacyPolicyTitle: "Privacy Policy",
        privacyIntro: "Your privacy is important to us. Here you can find how your data is processed when using the Luminex platform.",
        privacySection1: "Data Security",
        privacySection1Text: "All your data is encrypted with 256-bit SSL certificates and stored on secure servers.",
        // Cookie Policy
        cookiePolicyTitle: "Cookie Policy",
        cookieIntro: "We use cookies to provide you with a better experience.",
        cookieSection1: "Cookie Usage",
        cookieSection1Text: "The system uses mandatory cookies for session management and remembering your preferences.",
        resetPasswordTitle: "LUMINEX - Reset Password",
        resetPasswordHeader: "Reset Your Password",
        resetPasswordSubheader: "Please set a new and strong password for your account security.",
        resetPasswordText: "Please set a new and strong password for your account security.",
        backToLoginReset: "To return to the login screen ",
        resetPasswordFormTitle: "Reset Password",
        newPasswordLabel: "New Password",
        newPasswordPlaceholder: "Enter your new password",
        confirmNewPasswordLabel: "Confirm New Password",
        confirmNewPasswordPlaceholder: "Re-enter your new password",
        updatePasswordButton: "Update Password",
        dashboardTitle: "LUMINEX - Patient Dashboard",
        backToDashboardTitle: "Back to Dashboard",
        dashboardSidebar: "Dashboard",
        myAppointmentsSidebar: "My Appointments",
        doctorsBranchesSidebar: "Doctors / Branches",
        testResultsSidebar: "Tests & Results",
        radiologyResultsSidebar: "Radiology Images",
        prescriptionsSidebar: "My Prescriptions",
        healthHistorySidebar: "Health History",
        contactSupportSidebar: "Contact / Support",
        collapseMenu: "Collapse Menu",
        homePageHeader: "Home",
        notificationsTitle: "Notifications",
        all: "All",
        unread: "Unread",
        markAllAsRead: "Mark All as Read",
        noUnreadNotifications: "You have no unread notifications.",
        noNotificationsEver: "You don't have any notifications yet.",
        loginToSeeNotifications: "Please login to see your notifications.",
        nextAppointmentHeader: "Your Next Appointment",
        bookAppointmentQuick: "Book Appointment",
        viewTestResultsQuick: "View Test Results",
        myRadiologyImagesQuick: "My Radiology Images",
        doctorMessagesQuick: "Doctor Messages",
        doctorRatingQuick: "Doctor Evaluation",
        announcementsHealthTips: "Announcements & Health Tips",
        statisticsHeader: "Statistics",
        monthlyAppointmentsStats: "You completed {count} appointments this month.",
        adminDashboardTitle: "LUMINEX - Admin Panel",
        adminWelcomeMessage: "Welcome to Admin Panel!",
        loadingText: "Loading...",
        secureSession: "Secure Session",
        totalUsersLabel: "Total Users",
        lastWeekTrend: "vs last week",
        activeDoctorsLabel: "Active Doctors",
        newJoinersTrend: "New joiners",
        todayAppointmentsLabel: "Today's Appointments",
        increaseYesterdayTrend: "Increase vs yesterday",
        partnerHospitalsLabel: "Partner Hospitals",
        stableTrend: "Stable",
        appointmentActivityHeader: "Appointment Activity",
        thisWeekOption: "This Week",
        thisMonthOption: "This Month",
        quickActionsHeader: "Quick Actions",
        addUserQuickAction: "Add User",
        addHospitalQuickAction: "Add Hospital",
        getReportQuickAction: "Get Report",
        refreshSystemQuickAction: "Refresh System",
        systemStatusHeader: "System Status",
        databaseStatus: "Database",
        onlineStatus: "Online",
        apiServicesStatus: "API Services",
        uptimeStatus: "99.9% Uptime",
        backupStatus: "Backup",
        pendingStatus: "Pending",
        adminDashboardSidebar: "Dashboard",
        adminUsersSidebar: "Users",
        adminHospitalsSidebar: "Hospitals",
        adminDepartmentsSidebar: "Departments",
        adminReportsSidebar: "Reports",
        adminSupportRequestsSidebar: "Support Requests",
        userExistsError: 'A user with this National ID or Email already exists.',
        registerSuccess: 'REGISTRATION SUCCESSFUL!',
        fullNameRequired: 'Full Name cannot be empty.',
        tcIdInvalid: 'Please enter a valid National ID Number.',
        emailInvalid: 'Please enter a valid email address.',
        phoneInvalid: 'Please enter a valid phone number (10 digits).',
        passwordInvalid: 'Password must be at least 8 characters, contain uppercase/lowercase letters, numbers and special characters.',
        passwordMismatch: 'Passwords do not match.',
        ageInvalid: 'You must be over 18 years old.',
        termsRequired: 'Terms of use and KVKK text must be approved.',
        fieldRequired: 'This field cannot be empty.',
        loginToSeeReviews: "Please login to see your reviews.",
        noReviewsFoundPlaceholder: "You haven't made any reviews yet.",
        noReviewsFoundPlaceholderSubtext: "You can evaluate your doctors after your completed appointments.",
        deleteReview: "Delete",
        deleteReviewConfirm: "Are you sure?",
        deleteReviewConfirmMsg: "Are you sure you want to delete this review? This action cannot be undone.",
        yesDelete: "Yes, Delete",
        cancel: "Cancel",
        deleted: "Deleted!",
        reviewDeleted: "Your review has been successfully deleted.",
        myReviewsTitle: "My Reviews",
        myReviewsSidebar: "My Reviews",
        kvkkPageTitle: "LUMINEX - KVKK Clarification Text",
        kvkkMainHeader: "🔐 KVKK CLARIFICATION TEXT",
        kvkkIntroText: "As LUMINEX, we protect your personal data within the scope of the Personal Data Protection Law No. 6698 (“KVKK”).",
        dataController: "Data Controller",
        dataControllerText: "LUMINEX Health Technologies.",
        collectedData: "Collected Data",
        collectedDataText: "Name-surname, email address, phone number, birth date, gender, appointment history.",
        processingPurpose: "Data Processing Purpose",
        purposeItem1: "To conduct appointment processes,",
        purposeItem2: "To send reminder and information messages,",
        purposeItem3: "To improve service quality.",
        retentionPeriod: "Data Retention Period",
        retentionPeriodText: "Stored for a reasonable period within the scope of legal obligations and service continuity.",
        dataSharing: "Data Sharing",
        dataSharingText: "Your data is not shared with third parties; it can only be shared with necessary legal authorities.",
        userRights: "Your Rights",
        rightsItem1: "To access your personal data,",
        rightsItem2: "To request correction or deletion,",
        rightsItem3: "You have the right to object to processing.",
        kvkkContact: "Contact",
        kvkkContactText: "You can reach us at destek@luminex.com.tr for your requests.",
        kvkkFooter: "🔒 LUMINEX protects your personal data with care and always prioritizes your privacy.",
        termsPageTitle: "LUMINEX - Terms of Use",
        termsMainHeader: "TERMS OF USE",
        termsWelcomeText: "Welcome to LUMINEX.",
        termsIntroText: "This platform is designed to provide users with easy and secure access to healthcare services. By using the system, you agree to the following terms:",
        term1: "LUMINEX reserves the right to improve the appointment, information, and health guidance services it offers.",
        term2: "The user declares that the information provided when registering for the system is correct and up-to-date.",
        term3: "Transactions made on LUMINEX are for information and guidance purposes only; they do not constitute medical advice.",
        term4: "The user is responsible for the security of their account. They should not share their password with third parties.",
        term5: "LUMINEX cannot be held responsible for damages arising from incorrect or incomplete notifications made in the system.",
        term6: "The user can delete their account and remove their data from the system at any time.",
        term7: "Terms of use may be updated from time to time; the current version will always be available in this area.",
        termsFooter: "💡 By continuing to use the system, you are deemed to have accepted these terms.",
        backToRegisterBtn: "Back to Register Screen",
        backToHome: "Back to Home",
        readAndUnderstood: "I Read and Understood",
        errorTitle: "Error",
        contentLoadError: "Content could not be loaded.",
        tcRequired: "National ID Number cannot be empty.",
        passwordRequired: "Password cannot be empty.",
        ageRestriction: "Those under 18 cannot login.",
        passwordIncorrect: "The password you entered is incorrect. Please try again.",
        userNotFound: "No user found registered with this National ID Number.",
        tooManyAttempts: "Too many failed attempts. Please try again in {seconds} seconds.",
        accountTemporarilyLocked: "Your account has been temporarily locked.",
        attemptsRemaining: "({attempts} attempts remaining)",
        forgotTcInvalid: "Please enter a valid 11-digit National ID Number.",
        forgotFirstNameRequired: "Please enter your first name.",
        forgotLastNameRequired: "Please enter your last name.",
        forgotEmailInvalid: "Please enter a valid email address.",
        checkingInfo: "Checking your information...",
        infoVerifiedRedirecting: "Information verified! Redirecting...",
        userNotFoundForgot: "Error: No user found matching the information you entered.",
        editReview: "Edit",
        editYourReview: "Edit Your Review",
        saveChanges: "Save Changes",
        reviewUpdated: "Your review has been successfully updated.",
        invalidOrMissingResetToken: "Invalid or missing reset key. Please restart the password reset process.",
        enterNewPassword: "Please enter your new password.",
        confirmNewPassword: "Please confirm your new password.",
        passwordsDoNotMatch: "Passwords do not match.",
        passwordUpdateSuccess: "Your password has been successfully updated. Redirecting to login page...",
        invalidOrExpiredToken: "The reset key is invalid or has expired.",
        codeSentMessage: "Verification code has been sent to your email address.",
        enterVerificationCode: "Enter Verification Code",
        verifyCodeButton: "Verify Code",
        invalidCode: "The verification code you entered is invalid.",
        searchNotifications: "Search in notifications...",
        allCategories: "All Categories",
        categoryAppointment: "Appointments",
        categoryTestResult: "Test Results",
        categoryAlert: "Alerts",
        categorySystem: "System",
        allNotifications: "All Notifications",
        noNotificationsFound: "No notifications found matching your search criteria.",
        markAsRead: "Mark as Read",
        alreadyRead: "Read",
        today: "Today",
        yesterday: "Yesterday",
        contactHeroTitle: "How Can We Help You?",
        contactHeroSubtitle: "As the Luminex support team, we are always by your side.",
        callUs: "Call Us",
        callUsDesc: "You can reach us on weekdays between 09:00 - 18:00.",
        emailUs: "Send Us an Email",
        emailUsDesc: "You can write to us 24/7 for all your questions.",
        visitUs: "Visit Us",
        visitUsDesc: "We would be happy to host you in our central office.",
        showOnMap: "Show on Map",
        sendTicket: "Create a Support Request",
        selectSubject: "Select subject...",
        enterMessageDetails: "Please explain your message in detail...",
        ourLocation: "Our Location",
        faqTitle: "Frequently Asked Questions",
        // FAQ - Short keys (for HTML)
        faq1Q: "Can I integrate Luminex with my existing hospital system (HBYS)?",
        faq1A: "Yes, Luminex supports HL7 and FHIR standards. It works with 100% compatibility with your existing HBYS software, providing bidirectional integration without data loss.",
        faq2Q: "How is data security and KVKK compliance ensured?",
        faq2A: "All your data is encrypted with 256-bit SSL and stored in Tier-3 data centers in Turkey. Our system is fully compliant with KVKK and GDPR standards.",
        faq3Q: "How long does the setup and training process take?",
        faq3A: "Thanks to our cloud-based infrastructure, no installation is required. Your account is activated within 24 hours, and our 2-day online training program for your staff is free.",
        faq4Q: "What does your technical support service cover?",
        faq4A: "7/24 email support is standard across all our packages. With enterprise packages, you can get 7/24 phone support with a dedicated customer representative.",
        // FAQ - Long keys (existing)
        faq1Question: "Is LUMINEX paid?",
        faq1Answer: "No, booking appointments, viewing results, and using basic features are completely free for patients.",
        faq2Question: "Is my data secure?",
        faq2Answer: "Absolutely. Your data is protected with the latest encryption technologies and is shared with your doctors only with your permission.",
        faq3Question: "How can I book an appointment?",
        faq3Answer: "After registering for free, you can search for doctors by branch or name, see available times, and book an appointment with a single click.",
        faq4Question: "How can I see my test results?",
        faq4Answer: "After logging into your profile, you can instantly access all your laboratory and radiology results from the \"Health History\" section.",
        filter: "Filter",
        searchByDoctorName: "Search by doctor name...",
        searchByBranch: "Cardiology, Internal Medicine...",
        starRating: "Star Rating",
        allRatings: "All Ratings",
        fourStarsAbove: "4 Stars and Above",
        threeStarsAbove: "3 Stars and Above",
        twoStarsAbove: "2 Stars and Above",
        oneStarAbove: "1 Star and Above",
        doctorList: "Doctor List",
        allBranches: "All Branches",
        noDoctorsFound: "No doctors found matching your search criteria.",
        reviewsCount: "{count} reviews",
        readReviews: "Read Reviews",
        reviewsNotFoundTitle: "No Reviews Found",
        reviewsNotFoundText: "No reviews have been made for {name} yet.",
        averageRatingLabel: "Average Rating",
        pendingTickets: "Pending Requests",
        statusOpen: "Open",
        statusClosed: "Closed",
        startDate: "Start Date",
        endDate: "End Date",
        testName: "Test Name",
        searchByTestName: "Blood, urine...",
        outOfRangeOnly: "Only Out of Range",
        applyFilters: "Filter",
        clear: "Clear",
        noResultsFound: "No results found matching these criteria.",
        tryChangingFilters: "Try changing or clearing your filters.",
        dateLabel: "Date",
        doctorLabel: "Doctor",
        viewDetails: "View Details",
        downloadPdf: "Download PDF",
        outOfRangeValuesPresent: "(Out of Range Values Present)",
        referenceLabel: "Reference",
        outOfRangeWarning: "Result is out of reference range",
        inRangeInfo: "Result is within reference range",
        ok: "Got it",
        confirmTitle: "Confirmation",
        openReportInNewTab: "The report page will open in a new tab. Do you confirm?",
        yesOpen: "Yes, Open!",
        imagingType: "Imaging Type",
        searchByImagingType: "MRI, X-Ray...",
        viewReport: "View Report",
        openImages: "Open Images",
        technique: "Technique",
        findings: "Findings",
        resultComment: "Result / Comment",
        noInfo: "No info.",
        close: "Close",
        eventType: "Oyun Türü",
        appointmentEvent: "Polyclinic Appointment",
        testEvent: "Test Result",
        prescriptionEvent: "Prescription",
        radiologyEvent: "Radiology Result",
        testTitle: "Test Result",
        prescriptionTitle: "Prescription",
        radiologyTitle: "X-Ray Result",
        noHealthHistoryFound: "No health history record to display.",
        diagnosisLabel: "Diagnosis",
        details: "Details",
        statusUpcoming: "Upcoming",
        statusPast: "Past",
        statusCancelled: "Cancelled",
        statusWaiting: "Waiting",
        statusApproved: "Approved",
        noAppointmentsFound: "No appointments to display.",
        cancelAppointment: "Cancel",
        evaluate: "Evaluate",
        reschedule: "Reschedule",
        healthInfo: "Health Info",
        prescriptionDetail: "Prescription Detail",
        unspecifiedDiagnosis: "Diagnosis Not Specified",
        prescriptionDetailsTitle: "Prescription Details",
        preparing: "Preparing...",
        preparingDesc: "Generating prescription document",
        dosage: "Dosage",
        doctorNameLabel: "Doctor Name",
        statusLabel: "Status",
        myself: "Myself",
        locationInfo: "Location Info",
        provinceSelection: "Province Selection",
        typeOrSelectProvince: "Type or select province...",
        districtSelection: "District Selection",
        selectProvinceFirst: "Select Province First",
        hospitalSelection: "Hospital Selection",
        selectDistrictFirst: "Select District First",
        appointmentDetails: "Appointment Details",
        branchSelection: "Branch Selection",
        typeOrSelectBranch: "Type or select branch...",
        doctorSelection: "Doctor Selection",
        selectHospitalAndBranch: "Select Hospital and Branch",
        appointmentPerson: "Person Making Appointment",
        dateSelection: "Date Selection",
        availableHours: "Available Hours",
        selectDateFirst: "Please select a date.",
        importantHealthInfo: "Important Health Info",
        enterHealthInfoPlaceholder: "You can write your important health information here...",
        appointmentSummary: "Appointment Summary",
        timeLabel: "Time",
        notSelected: "Not Selected",
        notEntered: "Not Entered",
        confirmAppointment: "Confirm Appointment",
        // Branches
        cardiology: "Cardiology",
        internalMedicine: "Internal Medicine",
        orthopedics: "Orthopedics",
        ophthalmology: "Ophthalmology",
        pediatrics: "Pediatrics",
        generalSurgery: "General Surgery",
        gynecology: "Gynecology and Obstetrics",
        otolaryngology: "Otorhinolaryngology (ENT)",
        neurology: "Neurology",
        psychiatry: "Psychiatry",
        urology: "Urology",
        physicalTherapy: "Physical Therapy and Rehabilitation",
        dermatology: "Dermatology",
        pulmonology: "Pulmonology",
        infection: "Infectious Diseases",
        gastroenterology: "Gastroenterology",
        endocrinology: "Endocrinology",
        rheumatology: "Rheumatology",
        nephrology: "Nephrology",
        oncology: "Oncology",
        anesthesiology: "Anesthesiology and Reanimation",
        // Dashboard Widgets
        sunny: "Sunny",
        sunnyTip: "Sunny weather! A great day to store Vitamin D.",
        cloudy: "Partly Cloudy",
        cloudyTip: "The weather might be a bit cool, dress lightly when walking.",
        rainy: "Rainy",
        rainyTip: "Rain is abundance! Don't forget your umbrella if you go out.",
        medicineSuccessTitle: "Great!",
        medicineSuccessText: "Your medication tracking has been successfully recorded.",
        medicineTaken: "Taken ✓",
        monthlyAppointmentsStats: "You completed {count} appointments this month.",
        countdownDays: "Days",
        countdownHours: "Hrs",
        countdownMinsRemaining: "Mins left",
        countdownHeaderPrefix: "To your appointment:",
        examination: "Examination",
        waiting: "Waiting",
        completed: "Completed",
        confirmCancelTitle: "Are you sure?",
        confirmCancelText: "Are you sure you want to cancel this appointment?",
        yesCancel: "Yes, cancel it!",
        noStay: "No",
        cancelledTitle: "Cancelled!",
        cancelledText: "Your appointment has been successfully cancelled.",
        noHealthRecords: "No health records found yet.",
        // Health Tips
        tip_water: "Drink at least 8 glasses of water a day, keep your body and mind alive.",
        tip_exercise: "Regular exercise improves your heart health and reduces stress.",
        tip_flu: "Flu season is approaching, don't forget to get vaccinated and wear a mask in crowded environments.",
        tip_sleep: "Getting enough sleep strengthens your immune system and increases your energy.",
        tip_diet: "Eat a balanced diet: Consume plenty of fruits, vegetables, and whole grains.",
        tip_new_doc: "Our new Cardiology specialist Dr. Emre Aksoy has started accepting patients.",
        tip_sunscreen: "Using sunscreen reduces the risk of skin cancer and protects your skin.",
        tip_stress: "Try meditation or deep breathing exercises to manage stress.",
        tip_walking: "Walking for 30 minutes every day works wonders for your general health.",
        tip_parking: "Due to ongoing construction work at our hospital, there may be congestion in the parking lot.",
        tip_breakfast: "Don't skip breakfast, it's the most important meal of the day.",
        tip_smoke_alcohol: "Staying away from smoking and alcohol is critical for a long and healthy life.",
        tip_appointment_system: "Our online appointment system has been renewed! You can now book appointments faster and easier.",
        tip_checkup: "Don't neglect your regular doctor checkups, early diagnosis saves lives.",
        // Notifications
        notif_p_1_msg: "You have an appointment with Dr. Ayşe Yılmaz at the Cardiology Polyclinic tomorrow at 14:30.",
        notif_p_2_msg: "Your last Blood Test results are out. You can review them on the Results page.",
        notif_p_3_msg: "Medication Reminder: Don't forget to take your \"Parol\" medication on a full stomach.",
        notif_p_4_msg: "Our Luminex Mobile App has been updated! You can download it from the store to discover new features.",
        notif_p_5_msg: "Your Ophthalmology appointment has been successfully cancelled upon your request.",
        notif_p_6_msg: "Healthy Living Club: You are invited to this month's \"Diabetes and Nutrition\" seminar.",
        notif_a_1_msg: "A new user registration has been made: Mehmet Yılmaz. Waiting for approval.",
        notif_a_2_msg: "Server Disk space reached 80% capacity. Needs to be checked.",
        notif_a_3_msg: "A total of 15 new appointments were created for today.",
        notif_a_4_msg: "System backup process completed successfully.",
        notif_a_5_msg: "3 failed admin login attempts were detected in the last 24 hours.",
        notif_a_6_msg: "A new hospital registration is waiting to be reviewed: Private ABC Hospital.",
        // Index
        statsTitle: "LUMINEX in Numbers",
        happyPatients: "Happy Patients",
        specialistDoctors: "Specialist Doctors",
        partnerHospitals: "Contracted Hospitals",
        support247: "24/7 Support",
        testimonialsTitle: "What Do Our Patients Say?",
        testimonial1Text: '"Booking an appointment has never been this easy. I can view my test results instantly from my home. A wonderful system!"',
        testimonial1Author: "Ayşe Yılmaz",
        patientLabel: "Patient",
        testimonial2Text: '"Being able to communicate with my doctor was very important to me. Thanks to Luminex, I can ask the questions on my mind instantly."',
        testimonial2Author: "Mehmet Kaya",
        testimonial3Text: '"Having my entire health history in one place is a great convenience. No matter which doctor I go to, my information is with me."',
        testimonial3Author: "Zeynep Erdem",
        footerCompanyDesc: "A reliable health platform that offers innovative solutions in health technologies and builds the bridge between patient and doctor in the digital world.",
        corporateInfoTitle: "Corporate Info:",
        mersisNoLabel: "MERSIS No:",
        tradeRegistryNoLabel: "Trade Registry No:",
        taxNoLabel: "Tax No:",
        contactHours: "Weekdays: 09:00 - 18:00",
        contactEmailSupport: "24/7 Email Support",
        contactAddressLine1: "Luminex Plaza, Sisli",
        contactAddressLine2: "Istanbul, Turkey",
        quickLinksTitle: "Quick Links",
        home: "Home",
        loginRegisterLink: "Login / Register",
        trustSSL: "256-Bit SSL",
        trustSecure: "Secure Infrastructure",
        trustVerified: "Verified Platform",
        trustEtbis: "ETBIS Registered",
        footerCopyright: "© 2025 LUMINEX Health Technologies Inc. All rights reserved.",
        privacyPolicy: "Privacy Policy",
        termsOfUse: "Terms of Use",
        cookiePolicy: "Cookie Policy",
        // B2B / Corporate
        corporate: "Corporate",
        forClinics: "For Clinics",
        solutionsTitle: "Next Generation Solutions in Clinic Management",
        solutionsSubtitle: "Use Luminex in your own clinic, increase your efficiency by 40%.",
        b2bFeature1Title: "AI Powered Triage",
        b2bFeature1Text: "Your patients don't book appointments in the wrong department, your doctors' time is not wasted.",
        b2bFeature2Title: "White-Label Design",
        b2bFeature2Text: "Offer a tailored experience with your own logo and colors.",
        b2bFeature3Title: "Advanced Analytics",
        b2bFeature3Text: "Track branch workload and patient satisfaction in real-time.",
        demoRequest: "Request Demo",
        corporateContactTitle: "Bring Luminex to Your Clinic",
        corporateContactDesc: "Schedule a demo today and start your digital transformation.",
        // Pricing
        pricingTitle: "Flexible Plans for Clinics",
        pricingSubtitle: "Choose the plan that fits your needs, start digitizing today.",
        planBasic: "Basic",
        planStandard: "Professional",
        planPremium: "Enterprise",
        planSubtitlePro: "In addition to Basic plan",
        planSubtitleEnt: "In addition to Professional plan",
        featAppointment: "Online Appointment System",
        featPatients: "Unlimited Patient Records",
        featSMS: "SMS Notifications (500 units)",
        featAI: "AI Powered Triage",
        featWhiteLabel: "White-Label Experience",
        featAnalysis: "Advanced Analytics",
        featLab: "Lab Integration",
        featFull: "Unlimited Everything",
        featSupport: "24/7 Priority Support",
        featCustom: "Custom API Access",
        selectPlan: "Get Started",
        // Contact Form Specific
        warningTitle: "Warning",
        missingInfoTitle: "Missing Information",
        fillAllFields: "Please ensure all fields are filled out.",
        contactSuccessTitle: "Success!",
        contactSuccessText: "Your message has been sent successfully. We will get back to you shortly.",
        sendingMessage: "Sending...",
        sendingTitle: "Sending...",
        sendingText: "Your message is being sent, please wait.",
        genericErrorTitle: "Error!",
        genericErrorMessageServer: "A server error occurred. Please try again later.",
        genericErrorMessageNetwork: "A network error occurred. Please check your internet connection and try again.",
        okButton: "OK",
        // B2B Contact Form
        yourPosition: "Position",
        yourPhone: "Phone",
        companyName: "Clinic / Hospital Name",
        branchCount: "Number of Branches",
        dailyPatients: "Daily Patient Count",
        requestType: "Request Type",
        kvkkRequired: "You must approve the KVKK Clarification Text.",
        // Form Section Headers
        personalInfo: "Personal Information",
        corporateInfo: "Corporate Information",
        contactInfo: "Contact Information",
        requestDetails: "Request Details",
        // Placeholders
        namePlaceholder: "Your Name",
        emailPlaceholder: "example@clinic.com",
        phonePlaceholder: "05XX XXX XX XX",
        companyPlaceholder: "Your clinic or hospital name",
        messagePlaceholder: "Please describe your request in detail...",
        // Select Options
        selectOption: "Select",
        positionOwner: "Clinic Owner",
        positionManager: "Clinic Manager",
        positionDoctor: "Doctor",
        positionExecutive: "Executive",
        positionEmployee: "Employee",
        positionOther: "Other",
        branches1to5: "1-5 Branches",
        branches6to10: "6-10 Branches",
        branches11to20: "11-20 Branches",
        branches20plus: "20+ Branches",
        patientsLess50: "Less than 50",
        patients50to100: "50-100",
        patients100to200: "100-200",
        patients200plus: "200+",
        requestDemo: "Demo Request",
        requestPricing: "Pricing Info",
        requestTechnical: "Technical Questions",
        requestIntegration: "Integration Info",
        requestOther: "Other",
        // Contact Info Labels
        addressLabel: "Address",
        phoneLabel: "Phone",
        emailLabel: "Email",
        addressText: "Merkez Mah. Sağlık Sok. No:123, Istanbul",
        phoneText: "+90 (212) 555 00 00",
        emailText: "destek@luminex.com.tr",
        // KVKK
        kvkkApproveText: "I have read and approve the <a href=\"kvkk.html?lang=en\" style=\"color: var(--accent-color);\" data-lang=\"kvkkLinkText\">KVKK Clarification Text</a>. *",
        kvkkLinkText: "KVKK Clarification Text"
    }
};

const setLanguage = (lang) => {
    localStorage.setItem('language', lang);
    updateTexts(lang);
    updateSelectedLang(lang);
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { language: lang } }));
};

const updateTexts = (lang, rootElement = document) => {
    // Update elements with data-lang attribute
    rootElement.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.dataset.lang;
        if (translations[lang] && translations[lang][key]) {
            // Check if translation contains HTML (has < or >)
            const translation = translations[lang][key];
            if (translation.includes('<')) {
                // Use innerHTML for translations with HTML content
                el.innerHTML = translation;
            } else {
                // Use textContent for plain text
                el.textContent = translation;
            }
        }
    });

    // Update input/textarea placeholders with data-placeholder attribute
    rootElement.querySelectorAll('[data-placeholder]').forEach(el => {
        const key = el.dataset.placeholder;
        if (translations[lang] && translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });

    // Update select options with data-lang attribute
    rootElement.querySelectorAll('select option[data-lang]').forEach(el => {
        const key = el.dataset.lang;
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    // Legacy support for data-lang-placeholder
    rootElement.querySelectorAll('[data-lang-placeholder]').forEach(el => {
        const key = el.dataset.langPlaceholder;
        if (translations[lang] && translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });
};

const updateSelectedLang = (lang) => {
    const langData = {
        tr: { flag: 'tr', name: 'Türkçe' },
        en: { flag: 'gb', name: 'English' }
    };

    if (langData[lang]) {
        document.querySelectorAll('.selected-lang').forEach(selectedLangElement => {
            const img = selectedLangElement.querySelector('img');
            const span = selectedLangElement.querySelector('span');
            
            if (img) img.src = `https://flagcdn.com/${langData[lang].flag}.svg`;
            if (span) span.textContent = langData[lang].name;
        });
    }
};

const initLanguageSwitcher = () => {
    const langSwitchers = document.querySelectorAll('.lang-switcher');
    if (langSwitchers.length === 0) {
        return;
    }

    langSwitchers.forEach(langSwitcher => {
        const selectedLang = langSwitcher.querySelector('.selected-lang');
        const langOptions = langSwitcher.querySelector('.lang-options');

        if (selectedLang && langOptions) {
            // Remove old listeners by cloning
            const newSelectedLang = selectedLang.cloneNode(true);
            selectedLang.parentNode.replaceChild(newSelectedLang, selectedLang);

            newSelectedLang.addEventListener('click', (e) => {
                e.preventDefault();
                e.stopPropagation();

                langOptions.classList.toggle('show-lang-options');
                langSwitcher.classList.toggle('active');

                // Close all other lang options and remove active class
                document.querySelectorAll('.lang-switcher').forEach(ls => {
                    if (ls !== langSwitcher) {
                        ls.classList.remove('active');
                        const otherOptions = ls.querySelector('.lang-options');
                        if (otherOptions) otherOptions.classList.remove('show-lang-options');
                    }
                });
            });

            langOptions.querySelectorAll('li').forEach(li => {
                li.addEventListener('click', (e) => {
                    e.stopPropagation();
                    const lang = li.dataset.lang;
                    if (lang) {
                        setLanguage(lang);
                        langOptions.classList.remove('show-lang-options');
                        langSwitcher.classList.remove('active');
                    }
                });
            });
        }
    });

    // Close all when clicking anywhere else
    document.addEventListener('click', (e) => {
        if (!e.target.closest('.lang-switcher')) {
            document.querySelectorAll('.lang-switcher').forEach(ls => {
                ls.classList.remove('active');
                const opt = ls.querySelector('.lang-options');
                if (opt) opt.classList.remove('show-lang-options');
            });
        }
    });
};

document.addEventListener('DOMContentLoaded', () => {
    initLanguageSwitcher();
    // Initial language setting on page load
    const savedLang = localStorage.getItem('language') || 'tr';
    setLanguage(savedLang);
});

// Expose functions globally if needed by other scripts.
// In a more complex setup, consider using modules.
window.getTranslation = (key) => {
    const lang = localStorage.getItem('language') || 'tr';
    return (translations[lang] && translations[lang][key]) ? translations[lang][key] : key;
};
window.setLanguage = setLanguage;
window.updateTexts = updateTexts;
window.translations = translations;
window.initLanguageSwitcher = initLanguageSwitcher;